---
abstract: 'Return information on media (music, video, etc) file/URL'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Media-Info
requires:
  Media::Info::Mplayer: 0
  Perinci::CmdLine: 0
  Rinci: v1.1.40
  perl: 5.010001
resources: {}
version: 0.03
